### ISSUE TITLE
NumberFormat.getInstance() allocating lots of Memory

### ISSUE THREAD

**Issue by Entreco** [ursimon/CounterTextView#1]
Please put 'NumberFormat.getInstance()' in your BaseCounterTextView in a field variable.
Everytime display() is called, it needs to allocate memory.

```
abstract class BaseCounterTextView extends AppCompatTextView {
 private NumberFormat numberFormat = NumberFormat.getInstance();

private void display(long current) {
        if (mNumberFormat) {
            setText(numberFormat.format(current));
        } else {
            setText(String.valueOf(current));
        }
    }
}
```

I created a PullRequest here https://github.com/ursimon/CounterTextView/pull/2

**Comment by ursimon** [comment]
Oh, thanks. I thought it's a singleton, but you are right - it's creating new instance every time. I will test and merge your pull request.

**Comment by Entreco** [comment]
Thanks for the merge and spending time to create this library. Much appreciated

**Comment by ursimon** [comment]
I've developed it as a part of [Minitris](https://play.google.com/store/apps/details?id=com.ucisoftware.minitris) - then open sourced it, so basically you helped improve that as well. Beauty of open-source!
