### ISSUE TITLE
Good Idea

### ISSUE THREAD

**Issue by Florianisme** [ursimon/CounterTextView#3]
but why don't you just use a ValueAnimator with a custom Interpolator? :smile: 
Less dependencies and less code!

**Comment by ursimon** [comment]
I have't thought about it; I haven't designed this component from scratch it was more or less extracted from http://minitris.com game I've developed and I just wanted to share it with community.

Your suggestion make sense and is worth exploring. Not sure if I will pursue it. Feel free to fork it 😄
